name: opsless/ms-teams-github-actions
description: Microsoft Teams Github Actions integration
author: opsless.io team
inputs:
  github-token:
    required: true
    description: Github token
  webhook-uri:
    required: true
    description: MS Teams webhook URI
runs:
  using: node24
  main: dist/main/index.js
branding:
  icon: truck
  color: green